### ISSUE TITLE
This line may not required

### ISSUE THREAD

**Issue by ravinsinghd** [getcloudcherry/cloudcherry-web-microsurvey#40]
https://github.com/getcloudcherry/cloudcherry-web-microsurvey/blob/f272675df32111417f90fc00f65c80c0b6289bbb/src/SurveyHandler.ts#L213

you can pass null for tableID. Example the random number may not required. 
@prasath-k am i correct?

Example:
https://api.getcloudcherry.com/api/SurveyByToken/SR-72302/null

**Comment by venkateshwarv** [comment]
Fixed
